version: '3.1'
services:
  mysql-master:
    image: mysql:8.0.32
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - ./master/data:/var/lib/mysql
    networks:
      - mysql-cluster
      
  mysql-slave1:
    image: mysql:8.0.32
    container_name: mysql-slave1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3308:3306"
    volumes:
      - ./slave1/my.cnf:/etc/mysql/my.cnf
      - ./slave1/data:/var/lib/mysql
    networks:
      - mysql-cluster
    depends_on:
      - mysql-master

  mysql-slave2:
    image: mysql:8.0.32
    container_name: mysql-slave2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3309:3306"
    volumes:
      - ./slave2/my.cnf:/etc/mysql/my.cnf
      - ./slave2/data:/var/lib/mysql
    networks:
      - mysql-cluster
    depends_on:
      - mysql-master
      
  sharding-proxy:
    image: apache/shardingsphere-proxy:5.2.1
    restart: always
    container_name: sharding-proxy
    ports:
      - "3310:3310"  # 映射端口，外部访问此端口连接到 ShardingSphere-Proxy
    volumes:
      - ./shardingsphere-proxy/conf:/opt/shardingsphere-proxy/conf
      - ./shardingsphere-proxy/ext-lib:/opt/shardingsphere-proxy/ext-lib
      - ./shardingsphere-proxy/logs:/opt/shardingsphere/logs  
    networks:
      - mysql-cluster
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2
      
networks:
  mysql-cluster:
    driver: bridge