spring:
  application:
    name: sample-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    这是我的虚拟机
    url: jdbc:mysql://192.168.1.133:3310/order_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      #    这是我的虚拟机
      host: 192.168.1.133
      password: 123456
      port: 6379
      connect-timeout: 5000

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hixtrip.sample.infra.db.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'sample'
      paths-to-match: '/**'
      packages-to-scan: com.hixtrip.sample.entry
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn